name: "remove_arraycolumns"
description: remove array columns in a TTree
url:
authors:
  - Anfeng Li
input:
  - TTree ROOT file
output:
  - TTree ROOT file
params:
  input_tree_name: input_tree_name
  output_tree_name: output_tree_name
  dtfvar_namepattern: dtfvar_namepattern
