name: "tmva_classification_plot"
description: plot MVA training results
authors:
  - Anfeng Li
input:
  input_filepath: input_filepath
output:
  - expand("<any_path>/TMVAdataset/plots/variables_id_c{i}.png", i=range(1, math.ceil(len(training_variables) / 6) + 1))
  - "<any_path>/TMVAdataset/plots/CorrelationMatrixS.png"
  - "<any_path>/TMVAdataset/plots/CorrelationMatrixB.png"
  - "<any_path>/TMVAdataset/plots/mva_BDTG.png"
  - "<any_path>/TMVAdataset/plots/overtrain_BDTG.png"
  - "<any_path>/TMVAdataset/plots/mvaeffs_BDTG.png"
params:
  nsignal: number of signal for calculating FoM
  nbackground: number of background for calculating FoM
