name: "tmva_classification_plot"
description: plot MVA training results
authors:
  - Anfeng Li
input:
  input_filepath: input_filepath
output:
  - "<any_path>/TMVAdataset/plots/variables_id_c1.png"
  - "<any_path>/TMVAdataset/plots/variables_id_c2.png"
  - "<any_path>/TMVAdataset/plots/variables_id_c3.png"
  - "<any_path>/TMVAdataset/plots/CorrelationMatrixS.png"
  - "<any_path>/TMVAdataset/plots/CorrelationMatrixB.png"
  - "<any_path>/TMVAdataset/plots/mva_BDTG.png"
  - "<any_path>/TMVAdataset/plots/overtrain_BDTG.png"
  - "<any_path>/TMVAdataset/plots/mvaeffs_BDTG.png"
